"""Generate reviewable loading and validation GSQL from the table contract."""

from .contract import DATASETS, GRAPH, VERTICES

QUERY = "mt_validate_graph"


def loading_jobs() -> str:
    blocks = [
        f"// Generated by scripts/generate_mule_gsql.py. Vertices precede every edge.\nUSE GRAPH {GRAPH}\n"
    ]
    for d in DATASETS:
        source = {name: f"${i}" for i, name in enumerate(d.columns)}
        # Underscores preserve defaults for supervision clocks/masks and caches;
        # neither label availability nor time encodings can be inferred here.
        values = ", ".join(source.get(name, "_") for name, _ in d.graph_fields)
        blocks.append(f"""CREATE LOADING JOB {d.job} FOR GRAPH {GRAPH} {{
  DEFINE FILENAME data;
  LOAD data TO {"VERTEX" if d.vertex else "EDGE"} {d.name} VALUES ({values})
    USING SEPARATOR="|", HEADER="false", EOL="\\n";
}}
""")
    return "\n".join(blocks)


def verify_query() -> str:
    blocks = [
        f"""// Generated by scripts/generate_mule_gsql.py. Counts use store traversals,
// including reverse edges, rather than eventually consistent outdegree stats.
USE GRAPH {GRAPH}
CREATE OR REPLACE QUERY {QUERY}() FOR GRAPH {GRAPH} SYNTAX v2 {{
  MapAccum<STRING, SumAccum<INT>> @@counts;
  MapAccum<INT, SumAccum<INT>> @@account_mule_flags;
  SumAccum<INT> @@violations;
"""
    ]
    for d in VERTICES:
        if "first_seen_seq" in d.columns:
            invalid = "v.first_seen_seq == 0 OR v.first_seen_ts_ms == 0"
            if d.name == "Account":
                invalid += " OR v.is_mule < -1 OR v.is_mule > 1"
        else:
            invalid = "v.event_seq == 0 OR v.event_ts_ms == 0 OR v.amount < 0 OR (v.amount_present == FALSE AND v.amount != 0)"
            if d.name == "Payment_Transaction":
                invalid += ' OR v.payment_rail == "zelle"'
            else:
                invalid += " OR (v.label_known AND (v.fraud_label < 0 OR v.fraud_label > 1 OR v.label_available_seq <= v.event_seq OR v.label_available_ts_ms < v.event_ts_ms)) OR (v.label_known == FALSE AND (v.fraud_label != -1 OR v.label_available_seq != 0 OR v.label_available_ts_ms != 0))"
        extra = (
            ", @@account_mule_flags += (v.is_mule -> 1)" if d.name == "Account" else ""
        )
        blocks.append(
            f'  scan_{d.name} = SELECT v FROM {d.name}:v ACCUM @@counts += ("{d.name}" -> 1){extra}, IF {invalid} THEN @@violations += 1 END;'
        )
    for d in DATASETS[len(VERTICES) :]:
        if d.association:
            invalid = "e.valid_from_seq == 0 OR (e.valid_to_seq != 0 AND e.valid_to_seq <= e.valid_from_seq) OR s.first_seen_seq > e.valid_from_seq OR t.first_seen_seq > e.valid_from_seq OR e.confidence < 0 OR e.confidence > 1"
        else:
            invalid = "e.event_seq != s.event_seq OR e.event_ts_ms != s.event_ts_ms OR t.first_seen_seq > e.event_seq OR t.first_seen_ts_ms > e.event_ts_ms"
        blocks.append(
            f'  scan_{d.name} = SELECT s FROM {d.source}:s -({d.name}>:e)- {d.target}:t ACCUM @@counts += ("{d.name}" -> 1), IF {invalid} THEN @@violations += 1 END;'
        )
        blocks.append(
            f'  scan_{d.reverse} = SELECT t FROM {d.target}:t -({d.reverse}>:e)- {d.source}:s ACCUM @@counts += ("{d.reverse}" -> 1), IF {invalid} THEN @@violations += 1 END;'
        )
    blocks.append(
        f"  PRINT @@counts AS counts, @@account_mule_flags AS account_mule_flags, @@violations AS violations;\n}}\nINSTALL QUERY {QUERY}\n"
    )
    return "\n".join(blocks)
